/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carcare;

import carcare.controller.BillcccJpaController;
import carcare.controller.BillcceJpaController;
import carcare.controller.CustdataJpaController;
import carcare.model.Billccc;
import carcare.model.Billcce;
import carcare.model.Custdata;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author lenovo
 */
public class AddBilling extends javax.swing.JInternalFrame {

    CustdataJpaController custdataJpaController = new CustdataJpaController(CarCare.EMF);
    BillcccJpaController billcccJpaController = new BillcccJpaController(CarCare.EMF);
    BillcceJpaController billcceJpaController = new BillcceJpaController(CarCare.EMF);
    
    public AddBilling() {
        initComponents();
        
        DocumentFilter filter = new UppercaseDocumentFilter ();
        ((AbstractDocument) txtVNo.getDocument()).setDocumentFilter(filter);
        ((AbstractDocument) txtName.getDocument()).setDocumentFilter(filter);
        ((AbstractDocument) txtAddr.getDocument()).setDocumentFilter(filter);
        ((AbstractDocument) txtPhone.getDocument()).setDocumentFilter(filter);
        ((AbstractDocument) txtChashiNo.getDocument()).setDocumentFilter(filter);
        ((AbstractDocument) txtAddby.getDocument()).setDocumentFilter(filter);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        Date date = new Date();
        txtDate.setDate(date);
        
        jRadioButton1.setSelected(true);
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
    }
    
    void drawLines(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawLine(38, 455, 263, 455);
        g2d.drawLine(38, 479, 263, 479);
        
        g2d.drawLine(355, 430, 666, 430); 
        g2d.drawLine(355, 460, 666, 460);
    }
 
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        drawLines(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtChkAlign = new javax.swing.JTextField();
        txtAdstToe = new javax.swing.JTextField();
        txtCamber = new javax.swing.JTextField();
        txtCaster = new javax.swing.JTextField();
        txtBHight = new javax.swing.JTextField();
        txtReToe = new javax.swing.JTextField();
        txtReCamber = new javax.swing.JTextField();
        txtAnyOther = new javax.swing.JTextField();
        txtSusTest = new javax.swing.JTextField();
        txtHLTest = new javax.swing.JTextField();
        txtSubCCCTotal = new javax.swing.JTextField();
        txtDisCCCTotal = new javax.swing.JTextField();
        txtCCCTotal = new javax.swing.JTextField();
        chkFreeAlign = new javax.swing.JCheckBox();
        chkFreeToe = new javax.swing.JCheckBox();
        chkFreeCamb = new javax.swing.JCheckBox();
        chkFreeCast = new javax.swing.JCheckBox();
        chkFreeBHgt = new javax.swing.JCheckBox();
        chkFreeRToe = new javax.swing.JCheckBox();
        chkFreeRCam = new javax.swing.JCheckBox();
        chkFreeAnyO = new javax.swing.JCheckBox();
        chkFreeST = new javax.swing.JCheckBox();
        chkFreeHLT = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        txtOther2Qt = new javax.swing.JTextField();
        txtOther3Qt = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        txtDisCCETotal = new javax.swing.JTextField();
        txtOther3Txt = new javax.swing.JTextField();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtOther1Txt = new javax.swing.JTextField();
        txtOther2Txt = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        txtOther1Qt = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        txtSubCCETotal = new javax.swing.JTextField();
        txtCCETotal = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtVNo = new javax.swing.JTextField();
        txtChashiNo = new javax.swing.JTextField();
        txtMilage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtAddby = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Add Billing");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAR CARE CENTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Checking Align");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 120, -1));

        jLabel9.setText("Adjust Toe");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 45, 80, -1));

        jLabel10.setText("Camber");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, 80, -1));

        jLabel11.setText("Caster");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 80, -1));

        jLabel12.setText("Body Height");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 105, 80, -1));

        jLabel13.setText("Rear Toe");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, 80, -1));

        jLabel14.setText("Rear Camber");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 145, 120, -1));

        jLabel15.setText("Any Other");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 165, 80, 20));

        jLabel16.setText("Susp. Test");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 80, 20));

        jLabel17.setText("Head Light Test");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 205, 120, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("TOTAL");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 273, 80, -1));

        jLabel19.setText("Discount");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 253, 80, -1));

        jLabel20.setText("Sub Total");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 233, 90, -1));

        txtChkAlign.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChkAlignFocusLost(evt);
            }
        });
        txtChkAlign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChkAlignKeyTyped(evt);
            }
        });
        jPanel3.add(txtChkAlign, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, -1));

        txtAdstToe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdstToeFocusLost(evt);
            }
        });
        txtAdstToe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdstToeKeyTyped(evt);
            }
        });
        jPanel3.add(txtAdstToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, -1));

        txtCamber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCamberFocusLost(evt);
            }
        });
        txtCamber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamberKeyTyped(evt);
            }
        });
        jPanel3.add(txtCamber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 60, -1));

        txtCaster.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCasterFocusLost(evt);
            }
        });
        txtCaster.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCasterKeyTyped(evt);
            }
        });
        jPanel3.add(txtCaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, -1));

        txtBHight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBHightFocusLost(evt);
            }
        });
        txtBHight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBHightKeyTyped(evt);
            }
        });
        jPanel3.add(txtBHight, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 60, -1));

        txtReToe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReToeFocusLost(evt);
            }
        });
        txtReToe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReToeKeyTyped(evt);
            }
        });
        jPanel3.add(txtReToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, -1));

        txtReCamber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReCamberFocusLost(evt);
            }
        });
        txtReCamber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReCamberKeyTyped(evt);
            }
        });
        jPanel3.add(txtReCamber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 60, -1));

        txtAnyOther.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnyOtherFocusLost(evt);
            }
        });
        txtAnyOther.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnyOtherKeyTyped(evt);
            }
        });
        jPanel3.add(txtAnyOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 60, -1));

        txtSusTest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSusTestFocusLost(evt);
            }
        });
        txtSusTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSusTestKeyTyped(evt);
            }
        });
        jPanel3.add(txtSusTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 60, -1));

        txtHLTest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHLTestFocusLost(evt);
            }
        });
        txtHLTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHLTestKeyTyped(evt);
            }
        });
        jPanel3.add(txtHLTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 60, -1));

        txtSubCCCTotal.setEnabled(false);
        jPanel3.add(txtSubCCCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 60, -1));

        txtDisCCCTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDisCCCTotalFocusLost(evt);
            }
        });
        txtDisCCCTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisCCCTotalKeyTyped(evt);
            }
        });
        jPanel3.add(txtDisCCCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 60, -1));

        txtCCCTotal.setEnabled(false);
        jPanel3.add(txtCCCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 274, 60, -1));

        chkFreeAlign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeAlignMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeAlign, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        chkFreeToe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeToeMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        chkFreeCamb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeCambMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeCamb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        chkFreeCast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeCastMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeCast, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        chkFreeBHgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeBHgtMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeBHgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        chkFreeRToe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeRToeMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeRToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        chkFreeRCam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeRCamMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeRCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        chkFreeAnyO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeAnyOMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeAnyO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        chkFreeST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeSTMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeST, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        chkFreeHLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeHLTMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeHLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAR CARE ENTERPRISES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Fixed Camber Fr.");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 130, -1));

        jLabel22.setText("Fixed Camber Re.");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 130, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Amount");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 70, -1));

        jLabel24.setText("Wheel Balancing");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, 130, -1));

        jTextField20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField20FocusLost(evt);
            }
        });
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField20KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, 20));

        txtOther2Qt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOther2QtFocusLost(evt);
            }
        });
        txtOther2Qt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOther2QtKeyTyped(evt);
            }
        });
        jPanel5.add(txtOther2Qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 40, -1));

        txtOther3Qt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOther3QtFocusLost(evt);
            }
        });
        txtOther3Qt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOther3QtKeyTyped(evt);
            }
        });
        jPanel5.add(txtOther3Qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 40, -1));

        jTextField27.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField27FocusLost(evt);
            }
        });
        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField27KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 40, -1));

        jTextField28.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField28FocusLost(evt);
            }
        });
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField28KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 40, -1));

        jTextField29.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField29FocusLost(evt);
            }
        });
        jTextField29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField29KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 40, -1));

        jTextField30.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField30FocusLost(evt);
            }
        });
        jTextField30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField30KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 40, -1));

        jTextField31.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField31FocusLost(evt);
            }
        });
        jTextField31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField31KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 40, -1));

        jTextField32.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField32FocusLost(evt);
            }
        });
        jTextField32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField32KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, -1));

        jTextField33.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField33FocusLost(evt);
            }
        });
        jTextField33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField33KeyTyped(evt);
            }
        });
        jPanel5.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 40, -1));

        txtDisCCETotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDisCCETotalFocusLost(evt);
            }
        });
        txtDisCCETotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisCCETotalKeyTyped(evt);
            }
        });
        jPanel5.add(txtDisCCETotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 70, -1));
        jPanel5.add(txtOther3Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 110, -1));

        jCheckBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox11MouseClicked(evt);
            }
        });
        jPanel5.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 60, -1, -1));

        jCheckBox12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox12MouseClicked(evt);
            }
        });
        jPanel5.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 80, -1, -1));

        jCheckBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox13MouseClicked(evt);
            }
        });
        jPanel5.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 100, -1, -1));

        jCheckBox14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox14MouseClicked(evt);
            }
        });
        jPanel5.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 120, -1, -1));

        jLabel25.setText("Weights");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, 130, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Qty");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 40, -1));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Rate");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jLabel28.setText("Sub Total");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 205, 80, -1));

        jLabel29.setText("Discount");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 225, 80, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("TOTAL");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, -1));

        txtOther1Txt.setText("N2");
        txtOther1Txt.setEnabled(false);
        jPanel5.add(txtOther1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, 110, -1));

        txtOther2Txt.setText("Tyre Change");
        txtOther2Txt.setEnabled(false);
        jPanel5.add(txtOther2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 110, -1));

        jTextField21.setText("1");
        jTextField21.setEnabled(false);
        jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 40, -1));

        jTextField22.setText("1");
        jTextField22.setEnabled(false);
        jPanel5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, -1));

        jTextField23.setText("1");
        jTextField23.setEnabled(false);
        jPanel5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, -1));

        txtOther1Qt.setText("4");
        txtOther1Qt.setEnabled(false);
        jPanel5.add(txtOther1Qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 40, -1));

        jTextField34.setEnabled(false);
        jPanel5.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 70, -1));

        jTextField40.setEnabled(false);
        jPanel5.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 70, -1));

        jTextField39.setEnabled(false);
        jPanel5.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, -1));

        jTextField38.setEnabled(false);
        jPanel5.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 70, -1));

        jTextField41.setEnabled(false);
        jPanel5.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 70, -1));

        jTextField36.setEnabled(false);
        jPanel5.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70, 20));

        jTextField45.setEnabled(false);
        jPanel5.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, -1));

        txtSubCCETotal.setEnabled(false);
        jPanel5.add(txtSubCCETotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));

        txtCCETotal.setEnabled(false);
        jPanel5.add(txtCCETotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 70, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Date");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 64, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("V/ No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, 72, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Chasi No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, 72, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Millage");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 72, 25));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 25));

        txtVNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVNoFocusLost(evt);
            }
        });
        jPanel1.add(txtVNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, 25));
        jPanel1.add(txtChashiNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, 25));
        jPanel1.add(txtMilage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Payment Method");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 120, 25));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 330, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 70, 25));
        jPanel1.add(txtAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 330, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 25));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 105, 25));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Name");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 70, 25));

        jRadioButton1.setText("Cash");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jRadioButton2.setText("Credit");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));
        jPanel1.add(txtAddby, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 105, 25));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Add By");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChkAlignFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChkAlignFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtChkAlignFocusLost

    private void txtAdstToeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdstToeFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtAdstToeFocusLost

    private void txtCamberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCamberFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtCamberFocusLost

    private void txtCasterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCasterFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtCasterFocusLost

    private void txtBHightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBHightFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtBHightFocusLost

    private void txtReToeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReToeFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtReToeFocusLost

    private void txtReCamberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReCamberFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtReCamberFocusLost

    private void txtAnyOtherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnyOtherFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtAnyOtherFocusLost

    private void txtSusTestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusTestFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtSusTestFocusLost

    private void txtHLTestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHLTestFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtHLTestFocusLost

    private void txtDisCCCTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisCCCTotalFocusLost
        setCCCTotal();
    }//GEN-LAST:event_txtDisCCCTotalFocusLost

    private void chkFreeAlignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeAlignMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeAlignMouseClicked

    private void chkFreeToeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeToeMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeToeMouseClicked

    private void chkFreeCambMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeCambMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeCambMouseClicked

    private void chkFreeCastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeCastMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeCastMouseClicked

    private void chkFreeBHgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeBHgtMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeBHgtMouseClicked

    private void chkFreeRToeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeRToeMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeRToeMouseClicked

    private void chkFreeRCamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeRCamMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeRCamMouseClicked

    private void chkFreeAnyOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeAnyOMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeAnyOMouseClicked

    private void chkFreeSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeSTMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeSTMouseClicked

    private void chkFreeHLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeHLTMouseClicked
        setCCCTotal();
    }//GEN-LAST:event_chkFreeHLTMouseClicked

    private void txtChkAlignKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChkAlignKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtChkAlignKeyTyped

    private void txtAdstToeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdstToeKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtAdstToeKeyTyped

    private void txtCamberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamberKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtCamberKeyTyped

    private void txtCasterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCasterKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtCasterKeyTyped

    private void txtBHightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBHightKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtBHightKeyTyped

    private void txtReToeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReToeKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtReToeKeyTyped

    private void txtReCamberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReCamberKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtReCamberKeyTyped

    private void txtAnyOtherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnyOtherKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtAnyOtherKeyTyped

    private void txtSusTestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSusTestKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtSusTestKeyTyped

    private void txtHLTestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHLTestKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtHLTestKeyTyped

    private void txtDisCCCTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisCCCTotalKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtDisCCCTotalKeyTyped

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if(txtVNo.getText() == null || txtVNo.getText().equals("")){
            JOptionPane.showMessageDialog(jPanel1, "Please enter Vehicle no !");
            txtVNo.requestFocus();
        } else if(txtAddby.getText() == null || txtAddby.getText().equals("")){
            JOptionPane.showMessageDialog(jPanel1, "Please enter Add by !");
            txtAddby.requestFocus();
        } else {
            
            Billccc billccc = new Billccc();
            
            billccc.setVno(txtVNo.getText());
            billccc.setDate(txtDate.getDate());
            billccc.setName(txtName.getText());
            billccc.setAddress(txtAddr.getText());
            billccc.setPhone(txtPhone.getText());
            billccc.setMillage((txtMilage.getText() != null  && !txtMilage.getText().isEmpty()) ? Double.parseDouble(txtMilage.getText()) : 0);
            billccc.setChasiNo(txtChashiNo.getText());
            billccc.setPaymethod(jRadioButton1.isSelected());
            billccc.setAddby(txtAddby.getText());
            
            billccc.setChkAlign((txtChkAlign.getText() != null && !txtChkAlign.getText().isEmpty()) ? Integer.parseInt(txtChkAlign.getText()) : 0);
            billccc.setAjstToe((txtAdstToe.getText() != null && !txtAdstToe.getText().isEmpty()) ? Integer.parseInt(txtAdstToe.getText()) : 0);
            billccc.setCamber((txtCamber.getText() != null && !txtCamber.getText().isEmpty()) ? Integer.parseInt(txtCamber.getText()) : 0);
            billccc.setCaster((txtCaster.getText() != null && !txtCaster.getText().isEmpty()) ? Integer.parseInt(txtCaster.getText()) : 0);
            billccc.setBHight((txtBHight.getText() != null && !txtBHight.getText().isEmpty()) ? Integer.parseInt(txtBHight.getText()) : 0);
            billccc.setReToe((txtReToe.getText() != null && !txtReToe.getText().isEmpty()) ? Integer.parseInt(txtReToe.getText()) : 0);
            billccc.setReCamber((txtReCamber.getText() != null && !txtReCamber.getText().isEmpty()) ? Integer.parseInt(txtReCamber.getText()) : 0);
            billccc.setAnyOther((txtAnyOther.getText() != null && !txtAnyOther.getText().isEmpty()) ? Integer.parseInt(txtAnyOther.getText()) : 0);
            billccc.setSusTest((txtSusTest.getText() != null && !txtSusTest.getText().isEmpty()) ? Integer.parseInt(txtSusTest.getText()) : 0);
            billccc.setHLTest((txtHLTest.getText() != null && !txtHLTest.getText().isEmpty()) ? Integer.parseInt(txtHLTest.getText()) : 0);
            billccc.setDiscount((txtDisCCCTotal.getText() != null && !txtDisCCCTotal.getText().isEmpty()) ? Integer.parseInt(txtDisCCCTotal.getText()) : 0);            
            
            billccc.setFreeAlign(chkFreeAlign.isSelected());
            billccc.setFreeToe(chkFreeToe.isSelected());
            billccc.setFreeCamb(chkFreeCamb.isSelected());
            billccc.setFreeCast(chkFreeCast.isSelected());
            billccc.setFreeBhgt(chkFreeBHgt.isSelected());
            billccc.setFreeRToe(chkFreeRToe.isSelected());
            billccc.setFreeRCam(chkFreeRCam.isSelected());
            billccc.setFreeAnyo(chkFreeAnyO.isSelected());
            billccc.setFreeSt(chkFreeST.isSelected());
            billccc.setFreeHlt(chkFreeHLT.isSelected());
            
            billccc.setAmount((txtCCCTotal.getText() != null && !txtCCCTotal.getText().isEmpty()) ? Integer.parseInt(txtCCCTotal.getText()) : 0);            
            if(billccc.getAmount() > 0 ){
                billcccJpaController.create(billccc);
            }
            
            Billcce billcce = new Billcce();
            
            billcce.setVno(txtVNo.getText());
            billcce.setDate(txtDate.getDate());
            billcce.setName(txtName.getText());
            billcce.setAddress(txtAddr.getText());
            billcce.setPhone(txtPhone.getText());
            billcce.setMillage((txtMilage.getText() != null  && !txtMilage.getText().isEmpty()) ? Double.parseDouble(txtMilage.getText()) : 0);
            billcce.setChasiNo(txtChashiNo.getText());
            billcce.setPaymethod(jRadioButton1.isSelected());
            billcce.setAddby(txtAddby.getText());
            
            int chkAlign = !jCheckBox11.isSelected()? (Integer.parseInt(!jTextField27.getText().isEmpty() ? jTextField27.getText() : "0")) : 0 ;
            int adstToe = !jCheckBox12.isSelected()? (Integer.parseInt(!jTextField33.getText().isEmpty() ? jTextField33.getText() : "0")) : 0 ;
            int camber = !jCheckBox13.isSelected()? (Integer.parseInt(!jTextField32.getText().isEmpty() ? jTextField32.getText() : "0")) : 0 ;
            int caster = !jCheckBox14.isSelected()? (Integer.parseInt(!jTextField31.getText().isEmpty() ? jTextField31.getText() : "0")) : 0 ;
        
            billcce.setWbRa(chkAlign);
            billcce.setWRa(adstToe);
            billcce.setFixCmRF(camber);
            billcce.setFixCmRR(caster);
            billcce.setOther1Ra((jTextField30.getText() != null && !jTextField30.getText().isEmpty()) ? Integer.parseInt(jTextField30.getText()) : 0);
            billcce.setOther2Ra((jTextField29.getText() != null && !jTextField29.getText().isEmpty()) ? Integer.parseInt(jTextField29.getText()) : 0);
            billcce.setOther3Ra((jTextField28.getText() != null && !jTextField28.getText().isEmpty()) ? Integer.parseInt(jTextField28.getText()) : 0);
            
            billcce.setOTHER1Txt(txtOther1Txt.getText());
            billcce.setOTHER2Txt(jTextField32.getText());
            billcce.setOTHER3Txt(txtOther3Txt.getText());
            
            billcce.setWbQt(Integer.parseInt(!jTextField20.getText().isEmpty() ? jTextField20.getText() : "0"));
            billcce.setWQt(Integer.parseInt(!jTextField21.getText().isEmpty() ? jTextField21.getText() : "0"));
            billcce.setOther1Qt(Integer.parseInt(!txtOther1Qt.getText().isEmpty() ? txtOther1Qt.getText() : "0"));
            billcce.setOther2Qt(Integer.parseInt(!txtOther2Qt.getText().isEmpty() ? txtOther2Qt.getText() : "0"));
            billcce.setOther3Qt(Integer.parseInt(!txtOther3Qt.getText().isEmpty() ? txtOther3Qt.getText() : "0"));
            
            billcce.setFree1(jCheckBox11.isSelected());
            billcce.setFree2(jCheckBox12.isSelected());
            billcce.setFree3(jCheckBox13.isSelected());
            billcce.setFree4(jCheckBox14.isSelected());
            
            billcce.setDiscount((txtDisCCETotal.getText() != null && !txtDisCCETotal.getText().isEmpty()) ? Integer.parseInt(txtDisCCETotal.getText()) : 0);
            billcce.setAmount((txtCCETotal.getText() != null && !txtCCETotal.getText().isEmpty()) ? Integer.parseInt(txtCCETotal.getText()) : 0);                        
                        
            if(billcce.getAmount() > 0 ){
                billcceJpaController.create(billcce);                
            }
            
            if(billcce.getAmount() > 0 || billccc.getAmount() > 0 ){
                JOptionPane.showMessageDialog(jPanel1, "Successfuly save record !");
                dispose();
            }else{
                JOptionPane.showMessageDialog(jPanel1, "Bill amount Zero !");
            }
            
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jTextField27FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField27FocusLost
        int val1 = Integer.parseInt(!jTextField20.getText().isEmpty() ? jTextField20.getText() : "0"); 
        int val2 = Integer.parseInt(!jTextField27.getText().isEmpty() ? jTextField27.getText() : "0");         
        jTextField34.setText(Integer.toString(val1*val2));
        setCCETotal();
    }//GEN-LAST:event_jTextField27FocusLost

    private void jTextField33FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField33FocusLost
        jTextField40.setText(jTextField33.getText());
        setCCETotal();
    }//GEN-LAST:event_jTextField33FocusLost

    private void jTextField32FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField32FocusLost
        jTextField39.setText(jTextField32.getText());
        setCCETotal();
    }//GEN-LAST:event_jTextField32FocusLost

    private void jTextField31FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField31FocusLost
        jTextField38.setText(jTextField31.getText());
        setCCETotal();
    }//GEN-LAST:event_jTextField31FocusLost

    private void jTextField30FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField30FocusLost
        int outPut = Integer.parseInt(!jTextField30.getText().isEmpty() ? jTextField30.getText() : "0")*4; 
        jTextField41.setText(Integer.toString(outPut));
        setCCETotal();
    }//GEN-LAST:event_jTextField30FocusLost

    private void jTextField29FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField29FocusLost
        int val1 = Integer.parseInt(!txtOther2Qt.getText().isEmpty() ? txtOther2Qt.getText() : "0"); 
        int val2 = Integer.parseInt(!jTextField29.getText().isEmpty() ? jTextField29.getText() : "0");         
        jTextField36.setText(Integer.toString(val1*val2));
        setCCETotal();
    }//GEN-LAST:event_jTextField29FocusLost

    private void jTextField28FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField28FocusLost
        if(txtOther3Txt.getText() != null && !txtOther3Txt.getText().isEmpty()){
            int val1 = Integer.parseInt(!txtOther3Qt.getText().isEmpty() ? txtOther3Qt.getText() : "0"); 
            int val2 = Integer.parseInt(!jTextField28.getText().isEmpty() ? jTextField28.getText() : "0");         
            jTextField45.setText(Integer.toString(val1*val2));
            setCCETotal();
        }
    }//GEN-LAST:event_jTextField28FocusLost

    private void jTextField20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField20FocusLost
        int val1 = Integer.parseInt(!jTextField20.getText().isEmpty() ? jTextField20.getText() : "0"); 
        int val2 = Integer.parseInt(!jTextField27.getText().isEmpty() ? jTextField27.getText() : "0");         
        jTextField34.setText(Integer.toString(val1*val2));
        setCCETotal();
    }//GEN-LAST:event_jTextField20FocusLost

    private void txtOther2QtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOther2QtFocusLost
        int val1 = Integer.parseInt(!txtOther2Qt.getText().isEmpty() ? txtOther2Qt.getText() : "0"); 
        int val2 = Integer.parseInt(!jTextField29.getText().isEmpty() ? jTextField29.getText() : "0");         
        jTextField36.setText(Integer.toString(val1*val2));
        setCCETotal();
    }//GEN-LAST:event_txtOther2QtFocusLost

    private void txtOther3QtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOther3QtFocusLost
        if(txtOther3Txt.getText() != null && !txtOther3Txt.getText().isEmpty()){
            int val1 = Integer.parseInt(!txtOther3Qt.getText().isEmpty() ? txtOther3Qt.getText() : "0"); 
            int val2 = Integer.parseInt(!jTextField28.getText().isEmpty() ? jTextField28.getText() : "0");         
            jTextField45.setText(Integer.toString(val1*val2));
            setCCETotal();
        }
    }//GEN-LAST:event_txtOther3QtFocusLost

    private void txtDisCCETotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisCCETotalFocusLost
        setCCETotal();
    }//GEN-LAST:event_txtDisCCETotalFocusLost

    private void jCheckBox11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox11MouseClicked
        setCCETotal();
    }//GEN-LAST:event_jCheckBox11MouseClicked

    private void jCheckBox12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox12MouseClicked
        setCCETotal();
    }//GEN-LAST:event_jCheckBox12MouseClicked

    private void jCheckBox13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox13MouseClicked
        setCCETotal();
    }//GEN-LAST:event_jCheckBox13MouseClicked

    private void jCheckBox14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox14MouseClicked
        setCCETotal();
    }//GEN-LAST:event_jCheckBox14MouseClicked

    private void jTextField20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyTyped
        keyTyped(evt);
        if(jTextField20.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField20KeyTyped

    private void jTextField27KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyTyped
        keyTyped(evt);        
        if(jTextField27.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField27KeyTyped

    private void jTextField33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField33KeyTyped
        keyTyped(evt);
        if(jTextField33.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField33KeyTyped

    private void jTextField32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField32KeyTyped
        keyTyped(evt);
        if(jTextField32.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField32KeyTyped

    private void jTextField31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField31KeyTyped
        keyTyped(evt);
        if(jTextField31.getText().length()>=4) {
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextField31KeyTyped

    private void jTextField30KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField30KeyTyped
        keyTyped(evt);
        if(jTextField30.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField30KeyTyped

    private void jTextField29KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField29KeyTyped
        keyTyped(evt);
        if(jTextField29.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField29KeyTyped

    private void jTextField28KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyTyped
        keyTyped(evt);
        if(jTextField28.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField28KeyTyped

    private void txtOther2QtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOther2QtKeyTyped
        keyTyped(evt);
        if(txtOther2Qt.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOther2QtKeyTyped

    private void txtOther3QtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOther3QtKeyTyped
        keyTyped(evt);
        if(txtOther3Qt.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOther3QtKeyTyped

    private void txtDisCCETotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisCCETotalKeyTyped
        keyTyped(evt);
        if(txtDisCCETotal.getText().length()>=4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDisCCETotalKeyTyped

    private void txtVNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVNoFocusLost
        String vNo = txtVNo.getText() != null ? txtVNo.getText() : "";
        List<Custdata> cusdate = custdataJpaController.findCustdataByVno(vNo);
        
        if(cusdate != null && cusdate.size() > 0){                    
            Custdata cus = cusdate.get(0);
            txtName.setText(cus.getName());
            txtAddr.setText(cus.getAddress());
            txtPhone.setText(cus.getPhone());
            txtMilage.requestFocus();
        }else{
            txtName.setText("");
            txtAddr.setText("");
            txtPhone.setText("");
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtVNoFocusLost

    public void keyTyped(KeyEvent e) {
      char c = e.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        e.consume();
      }
    }
    
    private void setCCCTotal(){
        int outPut = 0;
        int chkAlign = !chkFreeAlign.isSelected()? (Integer.parseInt(!txtChkAlign.getText().isEmpty() ? txtChkAlign.getText() : "0")) : 0 ;
        int adstToe = !chkFreeToe.isSelected()? (Integer.parseInt(!txtAdstToe.getText().isEmpty() ? txtAdstToe.getText() : "0")) : 0 ;
        int camber = !chkFreeCamb.isSelected()? (Integer.parseInt(!txtCamber.getText().isEmpty() ? txtCamber.getText() : "0")) : 0 ;
        int caster = !chkFreeCast.isSelected()? (Integer.parseInt(!txtCaster.getText().isEmpty() ? txtCaster.getText() : "0")) : 0 ;
        int bHight = !chkFreeBHgt.isSelected()? (Integer.parseInt(!txtBHight.getText().isEmpty() ? txtBHight.getText() : "0")) : 0 ;
        int reToe = !chkFreeRToe.isSelected()? (Integer.parseInt(!txtReToe.getText().isEmpty() ? txtReToe.getText() : "0")) : 0 ;
        int reCamber = !chkFreeRCam .isSelected()? (Integer.parseInt(!txtReCamber.getText().isEmpty() ? txtReCamber.getText() : "0")) : 0 ;
        int anyOther = !chkFreeAnyO .isSelected()? (Integer.parseInt(!txtAnyOther.getText().isEmpty() ? txtAnyOther.getText() : "0")) : 0 ;
        int susTest = !chkFreeST.isSelected()? (Integer.parseInt(!txtSusTest.getText().isEmpty() ? txtSusTest.getText() : "0")) : 0 ;
        int hLTest = !chkFreeHLT.isSelected()? (Integer.parseInt(!txtHLTest.getText().isEmpty() ? txtHLTest.getText() : "0")) : 0 ;
        
        outPut = chkAlign + adstToe + camber + caster + bHight + reToe + reCamber + anyOther + susTest + hLTest;
        
        txtSubCCCTotal.setText(Integer.toString(outPut));
        int discount = Integer.parseInt(!txtDisCCCTotal.getText().isEmpty() ? txtDisCCCTotal.getText() : "0"); 
        txtCCCTotal.setText(Integer.toString(outPut > discount ? outPut - discount : 0));
    }
    
    private void setCCETotal(){
        int outPut = 0;
        int chkAlign = !jCheckBox11.isSelected()? (Integer.parseInt(!jTextField34.getText().isEmpty() ? jTextField34.getText() : "0")) : 0 ;
        int adstToe = !jCheckBox12.isSelected()? (Integer.parseInt(!jTextField40.getText().isEmpty() ? jTextField40.getText() : "0")) : 0 ;
        int camber = !jCheckBox13.isSelected()? (Integer.parseInt(!jTextField39.getText().isEmpty() ? jTextField39.getText() : "0")) : 0 ;
        int caster = !jCheckBox14.isSelected()? (Integer.parseInt(!jTextField38.getText().isEmpty() ? jTextField38.getText() : "0")) : 0 ;
        int bHight = Integer.parseInt(!jTextField41.getText().isEmpty() ? jTextField41.getText() : "0");
        int reToe = Integer.parseInt(!jTextField36.getText().isEmpty() ? jTextField36.getText() : "0");
        int reCamber = Integer.parseInt(!jTextField45.getText().isEmpty() ? jTextField45.getText() : "0");
        
        outPut = chkAlign + adstToe + camber + caster + bHight + reToe + reCamber;
        
        txtSubCCETotal.setText(Integer.toString(outPut));
        int discount = Integer.parseInt(!txtDisCCETotal.getText().isEmpty() ? txtDisCCETotal.getText() : "0"); 
        txtCCETotal.setText(Integer.toString(outPut > discount ? outPut - discount : 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkFreeAlign;
    private javax.swing.JCheckBox chkFreeAnyO;
    private javax.swing.JCheckBox chkFreeBHgt;
    private javax.swing.JCheckBox chkFreeCamb;
    private javax.swing.JCheckBox chkFreeCast;
    private javax.swing.JCheckBox chkFreeHLT;
    private javax.swing.JCheckBox chkFreeRCam;
    private javax.swing.JCheckBox chkFreeRToe;
    private javax.swing.JCheckBox chkFreeST;
    private javax.swing.JCheckBox chkFreeToe;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField txtAddby;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtAdstToe;
    private javax.swing.JTextField txtAnyOther;
    private javax.swing.JTextField txtBHight;
    private javax.swing.JTextField txtCCCTotal;
    private javax.swing.JTextField txtCCETotal;
    private javax.swing.JTextField txtCamber;
    private javax.swing.JTextField txtCaster;
    private javax.swing.JTextField txtChashiNo;
    private javax.swing.JTextField txtChkAlign;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDisCCCTotal;
    private javax.swing.JTextField txtDisCCETotal;
    private javax.swing.JTextField txtHLTest;
    private javax.swing.JTextField txtMilage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOther1Qt;
    private javax.swing.JTextField txtOther1Txt;
    private javax.swing.JTextField txtOther2Qt;
    private javax.swing.JTextField txtOther2Txt;
    private javax.swing.JTextField txtOther3Qt;
    private javax.swing.JTextField txtOther3Txt;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtReCamber;
    private javax.swing.JTextField txtReToe;
    private javax.swing.JTextField txtSubCCCTotal;
    private javax.swing.JTextField txtSubCCETotal;
    private javax.swing.JTextField txtSusTest;
    private javax.swing.JTextField txtVNo;
    // End of variables declaration//GEN-END:variables
}
