/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carcare;

import static carcare.CarCare.check_window;
import static carcare.CarCare.jDesktopPane1;
import static carcare.CarCare.view_check_window;
import static carcare.CarCare.authorizedUser;
import static carcare.CarCare.jDesktopPane1;
import static carcare.CarCare.user_window;
import carcare.controller.UserJpaController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;
import org.apache.commons.codec.digest.DigestUtils;
import org.apache.log4j.Logger;

/**
 *
 * @author Dinesh
 */
public class AuthorizedPanel extends javax.swing.JInternalFrame {

    private static final Logger logger = Logger.getLogger(AuthorizedPanel.class);   
    public static String loggUser;
    String panelType = "";
    
    public AuthorizedPanel() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        DocumentFilter filter = new UppercaseDocumentFilter ();
        ((AbstractDocument) txtUserName.getDocument()).setDocumentFilter(filter);
    }
    
    public AuthorizedPanel(String panelType) {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        DocumentFilter filter = new UppercaseDocumentFilter ();
        ((AbstractDocument) txtUserName.getDocument()).setDocumentFilter(filter);
        
        this.panelType = panelType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassWd = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Login");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 35, -1, -1));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 32, 160, -1));

        jLabel2.setText("PassWord  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 58, -1, -1));

        txtPassWd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassWdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassWd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 58, 161, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 89, 82, -1));

        btnExit.setText("Close");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 89, 75, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try{
            UserJpaController userJpaController = new UserJpaController(CarCare.EMF);
            String userName = txtUserName.getText();
            char[] passWd = txtPassWd.getPassword();
            String pwd = "";

            for(char pw : passWd){
                pwd = pwd + pw;
            }

            if (userName.isEmpty()) {
                JOptionPane.showMessageDialog(jPanel1, "Please Enter User Name !");
                txtUserName.requestFocus();
            }else{
                if (pwd.isEmpty()){
                    JOptionPane.showMessageDialog(jPanel1, "Please Enter Password !");
                    txtPassWd.requestFocus();
                }else{
                    String pw = DigestUtils.sha256Hex(pwd);
                    boolean authenticate;
                    if("addUser".equals(panelType)){
                        authenticate  = userJpaController.authenticateUserWithRole(userName, pw);
                    }else{
                        authenticate  = userJpaController.authenticateUser(userName, pw);
                    }

                    if(authenticate){
                        if("addUser".equals(panelType)){
                            if(user_window == 0){
                                AddUser user = new AddUser();
                                jDesktopPane1.add(user);
                                user.setVisible(true);
                                user_window = 1;
                                this.dispose();
                            }
                        }else{
                            if(view_check_window == 0 && check_window == 0){
                                loggUser = txtUserName.getText();
                                authorizedUser = true;
                                CheckSheet checkSheet = new CheckSheet();
                                jDesktopPane1.add(checkSheet);
                                checkSheet.setVisible(true);
                                view_check_window = 1;
                                this.dispose();
                            }
                        }
                    }else{
                        txtUserName.setText("");
                        txtPassWd.setText("");
                        txtUserName.requestFocus();
                        JOptionPane.showMessageDialog(jPanel1, "UserName and Passwd Combination Incorrect !");
                    }
                }
            }
        }catch(Exception e){
            logger.fatal("Error occured while log in to system -> "+ e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        txtPassWd.requestFocusInWindow();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPassWdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassWdActionPerformed
        btnLogin.requestFocusInWindow();
    }//GEN-LAST:event_txtPassWdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassWd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
