/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carcare;

import static carcare.ViewBill.EMF;
import carcare.controller.BillcccJpaController;
import carcare.controller.BillcceJpaController;
import carcare.controller.CustdataJpaController;
import carcare.controller.PaginationController;
import carcare.model.Billccc;
import carcare.model.Custdata;
import db.ConnectionManager;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class Billing1 extends javax.swing.JInternalFrame {

    public static EntityManagerFactory EMF = Persistence.createEntityManagerFactory("carcare?zeroDateTimeBehavior=convertToNullPU");
    CustdataJpaController custdataJpaController = new CustdataJpaController(EMF);
    BillcccJpaController billcccJpaController = new BillcccJpaController(EMF);
    BillcceJpaController billcceJpaController = new BillcceJpaController(EMF);
    
    public Billing1() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        Date date = new Date();
        txtDate.setDate(date);
    }
    
    void drawLines(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawLine(45, 587, 272, 587);
 
        g2d.drawLine(45, 610, 272, 610);
    }
 
    public void paint(Graphics g) {
        super.paint(g);
        drawLines(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtVNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddr = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtChkAlign = new javax.swing.JTextField();
        txtAdstToe = new javax.swing.JTextField();
        txtCamber = new javax.swing.JTextField();
        txtCaster = new javax.swing.JTextField();
        txtBHight = new javax.swing.JTextField();
        txtReToe = new javax.swing.JTextField();
        txtReCamber = new javax.swing.JTextField();
        txtAnyOther = new javax.swing.JTextField();
        txtSusTest = new javax.swing.JTextField();
        txtHLTest = new javax.swing.JTextField();
        txtSubCCCTotal = new javax.swing.JTextField();
        txtDisCCCTotal = new javax.swing.JTextField();
        txtCCCTotal = new javax.swing.JTextField();
        chkFreeAlign = new javax.swing.JCheckBox();
        chkFreeToe = new javax.swing.JCheckBox();
        chkFreeCamb = new javax.swing.JCheckBox();
        chkFreeCast = new javax.swing.JCheckBox();
        chkFreeBHgt = new javax.swing.JCheckBox();
        chkFreeRToe = new javax.swing.JCheckBox();
        chkFreeRCam = new javax.swing.JCheckBox();
        chkFreeAnyO = new javax.swing.JCheckBox();
        chkFreeST = new javax.swing.JCheckBox();
        chkFreeHLT = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtMilage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtChashiNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        txtAddby = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Billing");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Date");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 13, 64, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("V/ No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 45, 72, 25));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 13, 120, 25));

        txtVNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVNoFocusLost(evt);
            }
        });
        txtVNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVNoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtVNoMouseReleased(evt);
            }
        });
        jPanel1.add(txtVNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 45, 120, 25));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 280, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 70, 25));
        jPanel1.add(txtAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 280, 25));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Name");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("CAR CARE CENTER"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Checking Align");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 120, -1));

        jLabel9.setText("Adjust Toe");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 45, 80, -1));

        jLabel10.setText("Camber");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, 80, -1));

        jLabel11.setText("Caster");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 80, -1));

        jLabel12.setText("Body Height");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 105, 80, -1));

        jLabel13.setText("Rear Toe");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, 80, -1));

        jLabel14.setText("Rear Camber");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 145, 120, -1));

        jLabel15.setText("Any Other");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 165, 80, 20));

        jLabel16.setText("Susp. Test");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 185, 80, 20));

        jLabel17.setText("Head Light Test");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 205, 120, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("TOTAL");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 273, 80, -1));

        jLabel19.setText("Discount");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 253, 80, -1));

        jLabel20.setText("Sub Total");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 233, 90, -1));

        txtChkAlign.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChkAlignFocusLost(evt);
            }
        });
        txtChkAlign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChkAlignKeyTyped(evt);
            }
        });
        jPanel3.add(txtChkAlign, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, -1));

        txtAdstToe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdstToeFocusLost(evt);
            }
        });
        txtAdstToe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdstToeKeyTyped(evt);
            }
        });
        jPanel3.add(txtAdstToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, -1));

        txtCamber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCamberFocusLost(evt);
            }
        });
        txtCamber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamberKeyTyped(evt);
            }
        });
        jPanel3.add(txtCamber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 60, -1));

        txtCaster.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCasterFocusLost(evt);
            }
        });
        txtCaster.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCasterKeyTyped(evt);
            }
        });
        jPanel3.add(txtCaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, -1));

        txtBHight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBHightFocusLost(evt);
            }
        });
        txtBHight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBHightKeyTyped(evt);
            }
        });
        jPanel3.add(txtBHight, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 60, -1));

        txtReToe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReToeFocusLost(evt);
            }
        });
        txtReToe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReToeKeyTyped(evt);
            }
        });
        jPanel3.add(txtReToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, -1));

        txtReCamber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReCamberFocusLost(evt);
            }
        });
        txtReCamber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReCamberKeyTyped(evt);
            }
        });
        jPanel3.add(txtReCamber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 60, -1));

        txtAnyOther.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnyOtherFocusLost(evt);
            }
        });
        txtAnyOther.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnyOtherKeyTyped(evt);
            }
        });
        jPanel3.add(txtAnyOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 60, -1));

        txtSusTest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSusTestFocusLost(evt);
            }
        });
        txtSusTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSusTestKeyTyped(evt);
            }
        });
        jPanel3.add(txtSusTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 60, -1));

        txtHLTest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHLTestFocusLost(evt);
            }
        });
        txtHLTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHLTestKeyTyped(evt);
            }
        });
        jPanel3.add(txtHLTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 60, -1));

        txtSubCCCTotal.setEnabled(false);
        jPanel3.add(txtSubCCCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 60, -1));

        txtDisCCCTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDisCCCTotalFocusLost(evt);
            }
        });
        txtDisCCCTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDisCCCTotalKeyTyped(evt);
            }
        });
        jPanel3.add(txtDisCCCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 60, -1));

        txtCCCTotal.setEnabled(false);
        jPanel3.add(txtCCCTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 274, 60, -1));

        chkFreeAlign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeAlignMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeAlign, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        chkFreeToe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeToeMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        chkFreeCamb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeCambMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeCamb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        chkFreeCast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeCastMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeCast, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        chkFreeBHgt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeBHgtMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeBHgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        chkFreeRToe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeRToeMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeRToe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        chkFreeRCam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeRCamMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeRCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        chkFreeAnyO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeAnyOMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeAnyO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        chkFreeST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeSTMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeST, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        chkFreeHLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFreeHLTMouseClicked(evt);
            }
        });
        jPanel3.add(chkFreeHLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 301, 339));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("CAR CARE ENTERPRISES"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Fixed Camber Fr.");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 130, -1));

        jLabel22.setText("Fixed Camber Re.");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 130, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Amount");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 70, -1));

        jLabel24.setText("Wheel Balancing");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, 130, -1));
        jPanel5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, -1));
        jPanel5.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 40, -1));
        jPanel5.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 40, -1));
        jPanel5.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 40, -1));
        jPanel5.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 40, -1));
        jPanel5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 40, -1));
        jPanel5.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 40, -1));
        jPanel5.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 40, -1));
        jPanel5.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 40, -1));
        jPanel5.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 40, -1));
        jPanel5.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 70, -1));
        jPanel5.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 110, -1));

        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 60, -1, -1));

        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 80, -1, -1));

        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 100, -1, -1));

        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 120, -1, -1));

        jLabel25.setText("Weights");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, 130, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Qty");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 40, -1));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Rate");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, -1));

        jLabel28.setText("Sub Total");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 205, 80, -1));

        jLabel29.setText("Discount");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 225, 80, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("TOTAL");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, -1));

        jTextField43.setText("N2");
        jTextField43.setEnabled(false);
        jPanel5.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, 110, -1));

        jTextField42.setText("Tyre Change");
        jTextField42.setEnabled(false);
        jPanel5.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 110, -1));

        jTextField21.setText("1");
        jTextField21.setEnabled(false);
        jPanel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 40, -1));

        jTextField22.setText("1");
        jTextField22.setEnabled(false);
        jPanel5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 40, -1));

        jTextField23.setText("1");
        jTextField23.setEnabled(false);
        jPanel5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, -1));

        jTextField24.setText("4");
        jTextField24.setEnabled(false);
        jPanel5.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 40, -1));

        jTextField34.setEnabled(false);
        jPanel5.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 70, -1));

        jTextField40.setEnabled(false);
        jPanel5.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 70, -1));

        jTextField39.setEnabled(false);
        jPanel5.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, -1));

        jTextField38.setEnabled(false);
        jPanel5.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 70, -1));

        jTextField41.setEnabled(false);
        jPanel5.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 70, -1));

        jTextField36.setEnabled(false);
        jPanel5.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70, -1));

        jTextField45.setEnabled(false);
        jPanel5.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, -1));

        jTextField44.setEnabled(false);
        jPanel5.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, -1));

        jTextField46.setEnabled(false);
        jPanel5.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, -1));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 70, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 380, 339));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 420, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Phone");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 25));
        jPanel6.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 25));
        jPanel6.add(txtMilage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Millage");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 72, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Chasi No");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 72, 25));
        jPanel6.add(txtChashiNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Payment ");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 72, 25));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Cash");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Credit");
        jPanel6.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Add By");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 76, 25));
        jPanel6.add(txtAddby, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 25));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 250, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtVNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVNoFocusLost
        String vNo = txtVNo.getText() != null ? txtVNo.getText() : "";
        List<Custdata> cusdate = custdataJpaController.findCustdataByVno(vNo);
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Name", "Address", "Phone"}, 0);
        if(cusdate != null && cusdate.size() > 0){                    
            for (int i = 0; i < cusdate.size(); i++) {
                Custdata cus = cusdate.get(i);
                model.addRow(new Object[]{cus.getName(), cus.getAddress(), cus.getPhone()});
            }
            Custdata cus = cusdate.get(0);
            txtName.setText(cus.getName());
            txtAddr.setText(cus.getAddress());
            txtPhone.setText(cus.getPhone());
            txtMilage.requestFocus();
        }else{
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged(); 
            JOptionPane.showMessageDialog(jPanel1, "Vehicle number did not find !");
            
            txtName.setText("");
            txtAddr.setText("");
            txtPhone.setText("");
            txtName.requestFocus();
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_txtVNoFocusLost

    private void txtVNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVNoMouseClicked
        
    }//GEN-LAST:event_txtVNoMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        String name = jTable1.getModel().getValueAt(row, 0)!= null ? jTable1.getModel().getValueAt(row, 0).toString() : "";
        String address = jTable1.getModel().getValueAt(row, 1)!= null ? jTable1.getModel().getValueAt(row, 1).toString() : "";
        String phone = jTable1.getModel().getValueAt(row, 2)!= null ? jTable1.getModel().getValueAt(row, 2).toString() : "";
        
        txtName.setText(name);
        txtAddr.setText(address);
        txtPhone.setText(phone);
        txtMilage.requestFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtVNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVNoMouseReleased
        
    }//GEN-LAST:event_txtVNoMouseReleased

    private void txtChkAlignFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChkAlignFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtChkAlignFocusLost

    private void txtAdstToeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdstToeFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtAdstToeFocusLost

    private void txtCamberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCamberFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtCamberFocusLost

    private void txtCasterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCasterFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtCasterFocusLost

    private void txtBHightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBHightFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtBHightFocusLost

    private void txtReToeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReToeFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtReToeFocusLost

    private void txtReCamberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReCamberFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtReCamberFocusLost

    private void txtAnyOtherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnyOtherFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtAnyOtherFocusLost

    private void txtSusTestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSusTestFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtSusTestFocusLost

    private void txtHLTestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHLTestFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtHLTestFocusLost

    private void txtDisCCCTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDisCCCTotalFocusLost
        setCCTotal();
    }//GEN-LAST:event_txtDisCCCTotalFocusLost

    private void chkFreeAlignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeAlignMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeAlignMouseClicked

    private void chkFreeToeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeToeMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeToeMouseClicked

    private void chkFreeCambMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeCambMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeCambMouseClicked

    private void chkFreeCastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeCastMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeCastMouseClicked

    private void chkFreeBHgtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeBHgtMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeBHgtMouseClicked

    private void chkFreeRToeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeRToeMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeRToeMouseClicked

    private void chkFreeRCamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeRCamMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeRCamMouseClicked

    private void chkFreeAnyOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeAnyOMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeAnyOMouseClicked

    private void chkFreeSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeSTMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeSTMouseClicked

    private void chkFreeHLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFreeHLTMouseClicked
        setCCTotal();
    }//GEN-LAST:event_chkFreeHLTMouseClicked

    private void txtChkAlignKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChkAlignKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtChkAlignKeyTyped

    private void txtAdstToeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdstToeKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtAdstToeKeyTyped

    private void txtCamberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamberKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtCamberKeyTyped

    private void txtCasterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCasterKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtCasterKeyTyped

    private void txtBHightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBHightKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtBHightKeyTyped

    private void txtReToeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReToeKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtReToeKeyTyped

    private void txtReCamberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReCamberKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtReCamberKeyTyped

    private void txtAnyOtherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnyOtherKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtAnyOtherKeyTyped

    private void txtSusTestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSusTestKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtSusTestKeyTyped

    private void txtHLTestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHLTestKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtHLTestKeyTyped

    private void txtDisCCCTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDisCCCTotalKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_txtDisCCCTotalKeyTyped

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       System.out.println("hooooo - > " +buttonGroup1.getSelection().getActionCommand() + "--"+ jRadioButton1.isSelected()  + "--"+  jRadioButton2.isSelected());
        if(txtVNo.getText() == null || txtVNo.getText().equals("")){
            JOptionPane.showMessageDialog(jPanel1, "Please enter Vehicle no !");
            txtVNo.requestFocus();
        } else if(txtAddby.getText() == null || txtAddby.getText().equals("")){
            JOptionPane.showMessageDialog(jPanel1, "Please enter Add by !");
            txtAddby.requestFocus();
        } else {
            
            Billccc billccc = new Billccc();
            
            billccc.setVno(txtVNo.getText().trim().toUpperCase());
            billccc.setDate(txtDate.getDate());
            billccc.setName(txtName.getText() != null ? txtName.getText().trim().toUpperCase() : null);
            billccc.setAddress(txtAddr.getText() != null ? txtAddr.getText().trim().toUpperCase() : null);
            billccc.setPhone(txtPhone.getText() != null ? txtPhone.getText().trim().toUpperCase() : null);
            billccc.setMillage((txtMilage.getText() != null  && !txtMilage.getText().isEmpty()) ? Double.parseDouble(txtMilage.getText()) : 0);
            billccc.setChasiNo(txtChashiNo.getText() != null ? txtChashiNo.getText().trim().toUpperCase() : null);
            billccc.setPaymethod(jRadioButton1.isSelected());
            billccc.setAddby(txtAddby.getText());
            
            billccc.setChkAlign((txtChkAlign.getText() != null && !txtChkAlign.getText().isEmpty()) ? Integer.parseInt(txtChkAlign.getText()) : 0);
            billccc.setAjstToe((txtAdstToe.getText() != null && !txtAdstToe.getText().isEmpty()) ? Integer.parseInt(txtAdstToe.getText()) : 0);
            billccc.setCamber((txtCamber.getText() != null && !txtCamber.getText().isEmpty()) ? Integer.parseInt(txtCamber.getText()) : 0);
            billccc.setCaster((txtCaster.getText() != null && !txtCaster.getText().isEmpty()) ? Integer.parseInt(txtCaster.getText()) : 0);
            billccc.setBHight((txtBHight.getText() != null && !txtBHight.getText().isEmpty()) ? Integer.parseInt(txtBHight.getText()) : 0);
            billccc.setReToe((txtReToe.getText() != null && !txtReToe.getText().isEmpty()) ? Integer.parseInt(txtReToe.getText()) : 0);
            billccc.setReCamber((txtReCamber.getText() != null && !txtReCamber.getText().isEmpty()) ? Integer.parseInt(txtReCamber.getText()) : 0);
            billccc.setAnyOther((txtAnyOther.getText() != null && !txtAnyOther.getText().isEmpty()) ? Integer.parseInt(txtAnyOther.getText()) : 0);
            billccc.setSusTest((txtSusTest.getText() != null && !txtSusTest.getText().isEmpty()) ? Integer.parseInt(txtSusTest.getText()) : 0);
            billccc.setHLTest((txtHLTest.getText() != null && !txtHLTest.getText().isEmpty()) ? Integer.parseInt(txtHLTest.getText()) : 0);
            billccc.setDiscount(txtDisCCCTotal.getText() != null ? Integer.parseInt(txtDisCCCTotal.getText()) : 0);            
            
            billccc.setFreeAlign(chkFreeAlign.isSelected());
            billccc.setFreeToe(chkFreeToe.isSelected());
            billccc.setFreeCamb(chkFreeCamb.isSelected());
            billccc.setFreeCast(chkFreeCast.isSelected());
            billccc.setFreeBhgt(chkFreeBHgt.isSelected());
            billccc.setFreeRToe(chkFreeRToe.isSelected());
            billccc.setFreeRCam(chkFreeRCam.isSelected());
            billccc.setFreeAnyo(chkFreeAnyO.isSelected());
            billccc.setFreeSt(chkFreeST.isSelected());
            billccc.setFreeHlt(chkFreeHLT.isSelected());
            
            billccc.setAmount(txtCCCTotal.getText() != null ? Integer.parseInt(txtCCCTotal.getText()) : 0);
            billcccJpaController.create(billccc);
            
            
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    public void keyTyped(KeyEvent e) {
      char c = e.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        e.consume();
      }
    }
    
    private void setCCTotal(){
        int outPut = 0;
        int chkAlign = !chkFreeAlign.isSelected()? (Integer.parseInt(!txtChkAlign.getText().isEmpty() ? txtChkAlign.getText() : "0")) : 0 ;
        int adstToe = !chkFreeToe.isSelected()? (Integer.parseInt(!txtAdstToe.getText().isEmpty() ? txtAdstToe.getText() : "0")) : 0 ;
        int camber = !chkFreeCamb.isSelected()? (Integer.parseInt(!txtCamber.getText().isEmpty() ? txtCamber.getText() : "0")) : 0 ;
        int caster = !chkFreeCast.isSelected()? (Integer.parseInt(!txtCaster.getText().isEmpty() ? txtCaster.getText() : "0")) : 0 ;
        int bHight = !chkFreeBHgt.isSelected()? (Integer.parseInt(!txtBHight.getText().isEmpty() ? txtBHight.getText() : "0")) : 0 ;
        int reToe = !chkFreeRToe.isSelected()? (Integer.parseInt(!txtReToe.getText().isEmpty() ? txtReToe.getText() : "0")) : 0 ;
        int reCamber = !chkFreeRCam .isSelected()? (Integer.parseInt(!txtReCamber.getText().isEmpty() ? txtReCamber.getText() : "0")) : 0 ;
        int anyOther = !chkFreeAnyO .isSelected()? (Integer.parseInt(!txtAnyOther.getText().isEmpty() ? txtAnyOther.getText() : "0")) : 0 ;
        int susTest = !chkFreeST.isSelected()? (Integer.parseInt(!txtSusTest.getText().isEmpty() ? txtSusTest.getText() : "0")) : 0 ;
        int hLTest = !chkFreeHLT.isSelected()? (Integer.parseInt(!txtHLTest.getText().isEmpty() ? txtHLTest.getText() : "0")) : 0 ;
        
        outPut = chkAlign + adstToe + camber + caster + bHight + reToe + reCamber + anyOther + susTest + hLTest;
        
        txtSubCCCTotal.setText(Integer.toString(outPut));
        int discount = Integer.parseInt(!txtDisCCCTotal.getText().isEmpty() ? txtDisCCCTotal.getText() : "0"); 
        txtCCCTotal.setText(Integer.toString(outPut > discount ? outPut - discount : 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkFreeAlign;
    private javax.swing.JCheckBox chkFreeAnyO;
    private javax.swing.JCheckBox chkFreeBHgt;
    private javax.swing.JCheckBox chkFreeCamb;
    private javax.swing.JCheckBox chkFreeCast;
    private javax.swing.JCheckBox chkFreeHLT;
    private javax.swing.JCheckBox chkFreeRCam;
    private javax.swing.JCheckBox chkFreeRToe;
    private javax.swing.JCheckBox chkFreeST;
    private javax.swing.JCheckBox chkFreeToe;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField txtAddby;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtAdstToe;
    private javax.swing.JTextField txtAnyOther;
    private javax.swing.JTextField txtBHight;
    private javax.swing.JTextField txtCCCTotal;
    private javax.swing.JTextField txtCamber;
    private javax.swing.JTextField txtCaster;
    private javax.swing.JTextField txtChashiNo;
    private javax.swing.JTextField txtChkAlign;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDisCCCTotal;
    private javax.swing.JTextField txtHLTest;
    private javax.swing.JTextField txtMilage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtReCamber;
    private javax.swing.JTextField txtReToe;
    private javax.swing.JTextField txtSubCCCTotal;
    private javax.swing.JTextField txtSusTest;
    private javax.swing.JTextField txtVNo;
    // End of variables declaration//GEN-END:variables
}
