/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carcare;

import static carcare.CarCare.user_window;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Dinesh
 */
public class User extends javax.swing.JInternalFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        jRadioButton3.setSelected(true);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnAdd3 = new javax.swing.JButton();
        btnExit3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtConPassWd2 = new javax.swing.JPasswordField();
        txtPassWd2 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtUserName2 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtChgUserName = new javax.swing.JTextField();
        txtChgOldPwd = new javax.swing.JPasswordField();
        txtChgPassWd = new javax.swing.JPasswordField();
        txtChgConPassWd = new javax.swing.JPasswordField();
        btnChgAdd = new javax.swing.JButton();
        btnChgExit = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtUserName3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnChgAdd1 = new javax.swing.JButton();
        btnChgExit1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("User");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("User Name");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Password");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Confirm Password");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("User Role");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Active");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 142, 190));

        btnAdd3.setText("Add");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        jPanel8.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 75, 25));

        btnExit3.setText("Close");
        btnExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit3ActionPerformed(evt);
            }
        });
        jPanel8.add(btnExit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 75, 25));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtConPassWd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 30));
        jPanel1.add(txtPassWd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Regular User" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 30));
        jPanel1.add(txtUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jRadioButton4.setText("No");
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jRadioButton3.setText("Yes");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jPanel8.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 11, 200, 205));

        jTabbedPane3.addTab("Add User", jPanel8);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("User Name");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 120, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Old Password");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("New Password");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Confirm Password");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 30));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, 137, 160));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(txtChgUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 149, 30));
        jPanel13.add(txtChgOldPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 149, 30));
        jPanel13.add(txtChgPassWd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 149, 30));
        jPanel13.add(txtChgConPassWd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 30));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 21, 160, 170));

        btnChgAdd.setText("Add");
        btnChgAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgAddActionPerformed(evt);
            }
        });
        jPanel11.add(btnChgAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 75, 25));

        btnChgExit.setText("Close");
        btnChgExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgExitActionPerformed(evt);
            }
        });
        jPanel11.add(btnChgExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 75, 25));

        jTabbedPane3.addTab("Chage Password", jPanel11);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("User Name");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));
        jPanel14.add(txtUserName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 149, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Reset Password");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));
        jPanel14.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        btnChgAdd1.setText("Add");
        btnChgAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgAdd1ActionPerformed(evt);
            }
        });
        jPanel14.add(btnChgAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 75, 25));

        btnChgExit1.setText("Close");
        btnChgExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgExit1ActionPerformed(evt);
            }
        });
        jPanel14.add(btnChgExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 75, 25));

        jTabbedPane3.addTab("Reset Password", jPanel14);

        jPanel10.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 370, 310));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        /*try{
            UserQuery userQuery = new UserQuery();
            String userName = txtUserName.getText();
            char[] passWd = txtPassWd.getPassword();
            String pwd = "";

            for(char pw : passWd){
                pwd = pwd + pw;
            }

            char[] passWdCon = txtConPassWd.getPassword();
            String pwdCon = "";

            for(char pwCon : passWdCon){
                pwdCon = pwdCon + pwCon;
            }

            if (userName.isEmpty() || !Pattern.matches(RegularExpression.RE_NAME, userName)) {
                showPopupMessage(ErrorMessage.EM_USER_NAME);
                txtUserName.requestFocus();
            }else{
                if (userQuery.userAvailable(userName)) {
                    showPopupMessage(ErrorMessage.EM_USER_NAME_IN_DB);
                    txtUserName.requestFocus();
                }else{
                    if (pwd.isEmpty()){
                        showPopupMessage(ErrorMessage.EM_PW);
                        txtPassWd.requestFocus();
                    }else{
                        if (pwdCon.isEmpty()){
                            showPopupMessage(ErrorMessage.EM_CPW);
                            txtConPassWd.requestFocus();
                        }else{
                            if(!pwd.equalsIgnoreCase(pwdCon)){
                                showPopupMessage(ErrorMessage.EM_PW_CPW_NOT_MATCH);
                                txtConPassWd.requestFocus();
                            }else{
                                String pw = DigestUtils.sha256Hex(pwd);

                                User user = new User();
                                user.setUsername(userName);
                                user.setPasswd(pw);
                                user.setStatus("Y");

                                int userId = userQuery.createUser(user);
                                String msg;
                                if(userId > 0){
                                    msg = "You are successfully Add User !";
                                }else{
                                    msg = "Error Occured, Please try again !";
                                }
                                showPopupMessage(msg);
                                MainUi.window = 0;
                                dispose();
                            }
                        }
                    }
                }
            }
        }catch(Exception e){
            logger.fatal("Error occured while saving User -> " + e);
        }*/
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit3ActionPerformed
        dispose();
        user_window = 0;
    }//GEN-LAST:event_btnExit3ActionPerformed

    private void btnChgAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgAddActionPerformed
        /*try{
            UserQuery userQuery = new UserQuery();
            String userName = txtChgUserName.getText();
            char[] passWdOld = txtChgOldPwd.getPassword();

            String pwdOld = "";

            for(char pwOld : passWdOld){
                pwdOld = pwdOld + pwOld;
            }

            char[] passWd = txtChgPassWd.getPassword();
            String pwd = "";

            for(char pw : passWd){
                pwd = pwd + pw;
            }

            char[] passWdCon = txtChgConPassWd.getPassword();
            String pwdCon = "";

            for(char pwCon : passWdCon){
                pwdCon = pwdCon + pwCon;
            }

            if (userName.isEmpty() || !Pattern.matches(RegularExpression.RE_NAME, userName)) {
                showPopupMessage(ErrorMessage.EM_USER_NAME);
                txtChgUserName.requestFocus();
            }else{
                if (!userQuery.userAvailable(userName)) {
                    showPopupMessage(ErrorMessage.EM_USER_NAME_NOT_IN_DB);
                    txtChgUserName.requestFocus();
                }else{
                    if(pwdOld.isEmpty()){
                        showPopupMessage(ErrorMessage.EM_OLD_PW);
                        txtChgOldPwd.requestFocus();
                    }else{
                        String pwOld = DigestUtils.sha256Hex(pwdOld);
                        boolean authenticate  = userQuery.authenticateUser(userName, pwOld);
                        if(!authenticate){
                            showPopupMessage(ErrorMessage.EM_OLD_PW_STATUS);
                            txtChgOldPwd.requestFocus();
                        }else{
                            if (pwd.isEmpty()){
                                showPopupMessage(ErrorMessage.EM_NEW_PW);
                                txtChgPassWd.requestFocus();
                            }else{
                                if (pwdCon.isEmpty()){
                                    showPopupMessage(ErrorMessage.EM_CPW);
                                    txtChgConPassWd.requestFocus();
                                }else{
                                    if(!pwd.equalsIgnoreCase(pwdCon)){
                                        showPopupMessage(ErrorMessage.EM_PW_CPW_NOT_MATCH);
                                        txtChgConPassWd.requestFocus();
                                    }else{
                                        String pw = DigestUtils.sha256Hex(pwd);

                                        User user = new User();
                                        user.setUsername(userName);
                                        user.setPasswd(pw);

                                        int userId = userQuery.updateUser(user);
                                        String msg;
                                        if(userId > 0){
                                            msg = "You are successfully change user Password !";
                                        }else{
                                            msg = "Error Occured, Please try again !";
                                        }
                                        showPopupMessage(msg);
                                        MainUi.window = 0;
                                        dispose();
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }catch(Exception e){
            logger.fatal("Error occured while saving User -> " + e);
        }*/
    }//GEN-LAST:event_btnChgAddActionPerformed

    private void btnChgExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgExitActionPerformed
        dispose();
        user_window = 0;
    }//GEN-LAST:event_btnChgExitActionPerformed

    private void btnChgAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChgAdd1ActionPerformed

    private void btnChgExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgExit1ActionPerformed
        dispose();
        user_window = 0;
    }//GEN-LAST:event_btnChgExit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnChgAdd;
    private javax.swing.JButton btnChgAdd1;
    private javax.swing.JButton btnChgExit;
    private javax.swing.JButton btnChgExit1;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnExit3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPasswordField txtChgConPassWd;
    private javax.swing.JPasswordField txtChgOldPwd;
    private javax.swing.JPasswordField txtChgPassWd;
    private javax.swing.JTextField txtChgUserName;
    private javax.swing.JPasswordField txtConPassWd;
    private javax.swing.JPasswordField txtConPassWd1;
    private javax.swing.JPasswordField txtConPassWd2;
    private javax.swing.JPasswordField txtPassWd;
    private javax.swing.JPasswordField txtPassWd1;
    private javax.swing.JPasswordField txtPassWd2;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserName1;
    private javax.swing.JTextField txtUserName2;
    private javax.swing.JTextField txtUserName3;
    // End of variables declaration//GEN-END:variables
}
